[project]
name = "my_prog"
version = "1.0.0"
description = "Hello CLI"
requires-python = ">=3.11"

[project.scripts]
my_prog = "hello:main"


[tool.setuptools.package-data]
"in_dir.res_txt" = ["*.txt"]
