[project]
name = "my_gui_prog"
version = "1.0.0"
description = "Hello CLI"
requires-python = ">=3.11"

[project.gui-scripts]
my_gui_prog = "launch:main"


[tool.setuptools.package-data]
"in_dir.res_txt" = ["*.txt"]

[tool.setuptools.packages.find]
where = ["src/rec_n1"]
