[project]
name = "my_gui_prog"
version = "1.0.0"
description = "Hello CLI"
requires-python = ">=3.7"

[project.gui-scripts]
my_gui_prog = "launch:main"


[tool.setuptools.package-data]
"in_dir.res_txt" = ["res1/simple.ui"]

