[project]
name = "my_gui_prog"
version = "1.0.0"
description = "Test GUI"
requires-python = ">=3.11"
requires = ['pyside2>=5.15.0',
            'Pillow==7.1.2']
[project.gui-scripts]
my_gui_tst = "as_simple_as_it_gets:main"
