[project]
name = "my_gui_prog"
version = "1.0.0"
description = "HTML GUI"
requires-python = ">=3.11"

[project.gui-scripts]
my_prog = "test01:main"


[tool.setuptools.package-data]
"in_dir.res_txt" = ["*.html"]

[tool.setuptools.packages.find]
where = ["src/res1/simple.ui"]
